server:
  port: 8082
spring:
  kafka:
    consumer:
      bootstrap-servers: ${app.kafka.bootstrap}
      group-id: group-consumer-service
      auto-offset-reset: latest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: ${app.kafka.config.mapping}
        spring.json.value.default.type: ma.socrates.observability.consumer.core.model.Message

  application:
    name: observability-consumer-service
  datasource:
    url: jdbc:mysql://localhost:3306/observabiliy_db
    username: kafkauser
    password: kafkauserpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  kafka:
    bootstrap: PLAINTEXT://localhost:9090
    topic: topic-observability
    config:
      mapping: ma.socrates.observability.producer.core.model.Message:ma.socrates.observability.consumer.core.model.Message
