server:
  port: 8082
spring:
  application:
    name: observability-consumer-service
  kafka:
    bootstrap-servers: ${app.kafka.bootstrap}
  datasource:
    url: jdbc:mysql://localhost:3306/observabiliy_db
    username: kafkauser
    password: kafkauserpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
  kafka:
    bootstrap: PLAINTEXT://localhost:9090
    topic: topic-observability
    config:
      mapping: ma.socrates.observability.producer.core.model.Message:ma.socrates.observability.consumer.core.model.Message
